### ISSUE TITLE
How to work with submudules

### ISSUE THREAD

**Issue by pakimov2** [awslabs/git-remote-s3#14]
Hi 

Thank you for this project!
I have been successed with clone/push/pull commands with s3 remote. 
But when i try to add submodule with s3 remote, I get error:

```
$ git submodule add s3://my-backet-name/my-repo my-repo
Cloning into '/Volumes/data/my-repo'...
fatal: transport 's3' not allowed
```

Is it possible to use submudule command with s3 remote?

Thank you!

**Comment by pakimov2** [comment]
Resolved by:
`git config --global protocol.s3.allow always`

Thank you!

**Comment by massi-ang** [comment]
@pakimov2 thanks for the tip. I will add to the README.
