### ISSUE TITLE
not executing with native install but working in .venv - on Windows

### ISSUE THREAD

**Issue by KPq66dw8L** [awslabs/git-remote-s3#6]
After installing git-remote-s3 with pip I had this issue when trying to clone :

```
git clone s3://xxx/git-remote_xxx-iiot-cdk/
```
```
Cloning into 'git-remote_xxx-iiot-cdk'...
git: 'remote-s3' is not a git command. See 'git --help'.

The most similar command is
        remote-fd
fatal: remote helper 's3' aborted session
``` 

But it worked in a random python environment. 

Also if I add the ./venv/Scripts that contains the git-remote-s3.exe to my Path, I can clone from anywhere, but it will probably stop working if I ever delete the python environment I took the git-remote-s3.exe from.

**Comment by massi-ang** [comment]
Hi Julien, 

did you get a message like the following when you did `pip install git-remote-s3` without using virtual envs?

```
WARNING: The script xxxx.exe is installed in
'C:\Users\uuuuuu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.XX_xxxxxxx\
LocalCache\local-packages\Python310\Scripts' which is not on PATH.
 Consider adding this directory to PATH or, if you prefer to suppress this warning,
use --no-warn-script-location.
```

**Comment by KPq66dw8L** [comment]
Hi @massi-ang ,

I re-installed the package to check, and yes, I actually got this message. I just added this path to my PATH and everything works fine. Thanks !
